name: PR Checks (DEV)

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            test
            refactor
            ci
            docs
            chore
            wip # Work In Progress

          subjectPattern: ^[A-Z].+$
          subjectPatternError: |
            Description must start with a capital letter!
            For example: 'feat(api): Add new endpoint'

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0'

      - name: Restore dependencies
        run: dotnet restore YouMentor.slnx

      - name: Build
        run: dotnet build YouMentor.slnx --no-restore

      - name: Test
        run: dotnet test YouMentor.slnx --no-build
